/*
 * File: app/controller/Main.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SunshineBeauty.controller.MainController', {
    extend: 'Ext.app.Controller',

    models: [
        'Category'
    ],

    stores: [
        'Category'
    ],

    onCategorySelect: function(dataview, record, item, index, e, eOpts) {

    	var categoryDetailPanel, categoryName;
    	
    	categoryDetailPanel = dataview.up('treatmentsmanager');
    	categoryName = categoryDetailPanel.down('categorydetail displayfield#categoryName');
    	
    	//ajax call to get the category represented by record.data.id

        this.getCategoryModel().load(record.data.id, {

            success : function(categoryRecord) {

            	categoryName.setValue(categoryRecord.get('name'));
            	
            	categoryRecord.treatmentsStore.each(function(treatmentRecord) {

                    console.log(treatmentRecord.get('name'));

                });

            }
        });

        

    },

    init: function() {
        this.control({
            "#treatmentsManager #categoryGrid": {
                itemclick: this.onCategorySelect
            }
        });
    },

    onLaunch: function() {

    }

});
