/*
 * File: app/model/Category.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SunshineBeauty.model.Category', {
    extend: 'Ext.data.Model',

    uses: [
        'SunshineBeauty.model.Treatment'
    ],

    fields: [
        {
            name: 'id'
        },
        {
            name: 'name'
        }
    ],

    hasMany: [
        {
            associationKey: 'children',
            model: 'SunshineBeauty.model.Category',
            name: 'children'
        },
        {
            associationKey: 'treatments',
            model: 'SunshineBeauty.model.Treatment',
            name: 'treatments'
        }
    ],

    proxy: {
        type: 'rest',
        url: 'category/',
        reader: {
            type: 'json',
            root: 'data'
        }
    }
});