/*
 * File: app/view/BannerPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SunshineBeauty.view.BannerPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.bannerpanel',

    border: false,
    height: 100,
    margin: 8,
    layout: {
        type: 'border'
    },
    frameHeader: false,
    header: false,
    title: 'Banner',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'image',
                    region: 'north',
                    src: 'resources/images/banner.gif'
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    border: false,
                    bodyStyle: 'padding:0px 0px 0px 0px; width:805px; background:URL(resources/images/menu-background.gif);background-repeat:repeat-x; line-height:25px',
                    frameHeader: false,
                    header: false,
                    title: 'My Panel'
                }
            ]
        });

        me.callParent(arguments);
    }

});