/*
 * File: app/view/CategoryDetail.js
 *
 * This file was generated by Sencha Architect version 2.2.3.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SunshineBeauty.view.CategoryDetail', {
	extend : 'Ext.form.Panel',
	alias : 'widget.categorydetail',

	layout : {
		type : 'vbox',
	},

	// frameHeader: false,
	// header: false,
	border : false,

	initComponent : function() {
		var me = this;

		Ext.applyIf(me, {
			items : [ {
				xtype: 'panel',
				width: '100%',
				layout: 'column',
				items: [{
					xtype: 'panel',
					width: 200,
					html: 'IMAGE'
				},
				{
					xtype: 'displayfield',
					columnWidth: 1,
					name: 'name',
					itemId: 'categoryName',
					//align right!
					value : 'SELECTED CATEGORY LABEL',
				}],
			},{
				xtype: 'panel',
				width: '100%',
				layout: 'column',
				items: [{
					xtype: 'panel',
					width: 200,
					html: 'SPACER'
				},
				{
					xtype: 'panel',
					columnWidth: 1,
					//align right!
					html : 'GRID SHOWING CHILDREN',
				}],
			},
			{
			
				xtype : 'panel',
				width: '100%',
				html : 'TREATMENT LIST',
				border: false
			} ]
		});

		me.callParent(arguments);
	}

});